# set cache headers for filetypes

location ~* \.(jpg|jpeg|gif|png|webp|ico|gz|svg|svgz|mp4|webm|woff|woff2|ttf|eot|pdf)$ {
    etag on;
    if_modified_since exact;
    add_header Cache-Control "public, max-age=31536000";
}

location ~* \.(css|js)$ {
    etag on;
    if_modified_since exact;
    add_header Cache-Control "public, max-age=2678400";
}

location ~* \.(html|svg|txt|xsl|xml)$ {
    etag on;
    if_modified_since exact;
    add_header Cache-Control "public, max-age=3600";
}
